version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    # permission deniedが出ており、権限の与え方を調べるのがめんどくさいのでここだけ手動
    # command: "/docker-initialize.sh"
    volumes:
      # アクセスログ・エラーログを外部に保存する
      - ./logs/nginx:/var/log/nginx
      # 設定ファイルを外部に保存する
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Laravelプロジェクトと繋ぐ
      - ./codeIgniter_app:/var/www/codeIgniter_app

    ports:
      - 58910:80
    networks:
      - codeignater_network
    depends_on:
      # PHPの後に処理を実行しはじめる
      - phpfpm
    tty: true

  phpfpm:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    # command: "/docker-initialize.sh"
    volumes:
      - ./codeIgniter_app:/var/www/codeIgniter_app
    networks:
      - codeignater_network
    depends_on:
      - mysql
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    # command: "/docker-initialize.sh"
    volumes: 
      - ./logs/mysql:/var/log/mysql
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 58920:3306
    networks:
      - codeignater_network
    tty: true

networks:
  codeignater_network:
